version: '2'
services:
    miblog-app:
        image: miblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://miblog-mysql:3306/miblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=miblog-elasticsearch:9300
        ports:
            - 8080:8080
    miblog-mysql:
        extends:
            file: mysql.yml
            service: miblog-mysql
    miblog-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: miblog-elasticsearch
